# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifycode',
            name='url',
        ),
    ]
