# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 15:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=64)),
                ('cellphone', models.CharField(max_length=16)),
                ('address', models.CharField(blank=True, max_length=512)),
                ('head_img', models.ImageField(null=True, upload_to='image/%Y/%m/%d')),
                ('level', models.IntegerField(default=1)),
                ('current_stage', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='RealInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=64)),
                ('id_number', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='real_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.RealInfo'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
