# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20170408_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='verufy_code',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
