# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_myuser_verufy_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='verufy_code',
        ),
    ]
