# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_item_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='available',
        ),
        migrations.AddField(
            model_name='item',
            name='locking_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
